logging:
  level:
    org:
      springframework: warn

server:
  port: 8080
  servlet:
    contextPath: /auction

hibernate:
 id:
   new_generator_mappings: true

spring:

  flyway:
    enabled: false  # disable automatic migration

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/auction
    username: postgres
    password: $$$$$$$$$$$$$

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    password: $$$$$$$$$$$$$
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          timeout: 5000
          writetimeout: 5000
    username: kurm6886@gmail.com

redis:
  hostname: localhost
  port: 6379
  ttl: 10
  timeout: 2
  socketTimeout: 2







