logging:
  level:
    org:
      springframework: warn
server:
  servlet:
    contextPath: /auction
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:./data/auction
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml
  mail:
    host: smtp.gmail.com
    password: $$$$$$$$$$$$$
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          timeout: 5000
          writetimeout: 5000
    username: kurm6886@gmail.com

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379





